use university;

select course.course_name,section.instructor,section.year
from course
inner join section
on course.course_number=section.course_number
where instructor="King"and year in (7,8);

SELECT STUDENT.STUDENT_NUMBER,SECTION.INSTRUCTOR,SECTION.COURSE_NUMBER,SECTION.SEMESTER,SECTION.YEAR,count(STUDENT.STUDENT_NUMBER) FROM STUDENT 
INNER JOIN COURSE ON COURSE.DEPARTMENT=STUDENT.MAJOR INNER JOIN SECTION ON SECTION.COURSE_NUMBER=COURSE.COURSE_NUMBER
group by SECTION.SECTION_IDENTIFIER
HAVING SECTION.INSTRUCTOR="KING";

CREATE TABLE DEPARTMENT(EID INT PRIMARY KEY,ENAME VARCHAR(20),DESIGNATION VARCHAR(20),DOJ INT CONSTRAINT SAL_CHK CHECK(YEAR(DOJ)>1967) );


